version: '3'

services:
  sample-rabbit:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
  sample-redis:
    image: redis
    ports:
      - "6379:6379"
  sample-es:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
  sample-redis-ui:
    image: dmportella/redis-commander:latest
    ports: 
      - "8080:8080"